### ISSUE TITLE
The brick on the F5 key hangs the PHP subsystem (fpm)

### ISSUE THREAD

**Issue by ghost** [alimranahmed/LaraOCR#20]
If you look at processes from root or user via top or htop, you can see that php-fpm is running the tesseract at 100% CPU resources, and the more the more the load is. Just unfolding fractal of some kind.

The solution is to create either a "busy" .lock file or use a queue.

I recommend the .lock file because it is easy to implement and fast to scale.

Thank you for LaraOCR !

**Comment by ghost** [comment]
I understand that I may have an unfortunate solution (really made on the spot), but it's still worth closing a potential hole.

**Comment by alimranahmed** [comment]
Hi @h-zone, 
Thanks for reporting this issue. Unfortunately I am not being able to re-generate this issue. Can you please the steps to re-generate this issue so that I can fix if this is a common one.

**Comment by ghost** [comment]
as an option:
- reverse proxy nginx -> backent nginx with php8u0-fpm
- implementation via API
- any restful tool, such as insomnia
- click 10 times "send request" with an attached image
= the result is 10 parallel OCR processes
depending on the server capacity sooner or later, but i think no more than 25-30 simultaneous requests, we will get a denial of service. either 500 or 502 error

**Comment by alimranahmed** [comment]
@h-zone 

Thanks for your response. 

Can't this be handled the the user who implement this library. 
This is just a package that use `Tesseract` under the hood so that someone don't have to write the PHP connector of `Tesseract`. But All the request handling and others are still on user's sholder. The already view that is being shipped with this package is just a visual sample what can be done.
